version: '3'
services:
    apache:
        build: .docker/apache
        container_name: voltwatcher_apache
        ports:
          - 8001:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/voltwatcher
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: voltwatcher_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: .docker/php
        container_name: voltwatcher_php
        volumes:
          - .:/home/wwwroot/voltwatcher
        environment:
          APP_ENV: dev
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: voltwatcher_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8002:80
        links:
            - mysql

