version: '3'
services:
    app:
        image: manzolo/voltwatcher:latest
        #image: manzolo/voltwatcher:2.0.105
        restart: always
        container_name: voltwatcher
        volumes:
            - ./config/jwt:/var/www/html/config/jwt
        environment:
          APP_ENV: ${APP_ENV}
          DATABASE_URL: ${DATABASE_URL}
          JWT_PASSPHRASE: ${JWT_PASSPHRASE}
          MAILER_USER: ${MAILER_USER}
          OPENWEATHERMAP_APIKEY: ${OPENWEATHERMAP_APIKEY}
          MAILER_DSN: ${MAILER_DSN}
        env_file:
          - .env
        ports:
            - ${HTTP_PORT}:80
