version: '3'
services:
    apache:
        image: manzolo/voltwatcher_apache
        build: .docker/full/apache
        container_name: voltwatcher_apache
        ports:
          - ${APACHE_PORT}:80
        volumes:
          - .docker/full/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/voltwatcher
        environment:
            APACHE_PORT: ${APACHE_PORT}
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: voltwatcher_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        image: manzolo/voltwatcher_php
        build: .docker/full/php
        container_name: voltwatcher_php
        volumes:
          - .:/home/wwwroot/voltwatcher
        environment:
          APP_ENV: ${APP_ENV}
          DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@voltwatcher_mysql:3306/${MYSQL_DATABASE}
          JWT_PASSPHRASE: ${JWT_PASSPHRASE}
          MAILER_USER: ${MAILER_USER}
          OPENWEATHERMAP_APIKEY: ${OPENWEATHERMAP_APIKEY}
          MAILER_DSN: ${MAILER_DSN}
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: voltwatcher_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${PHPMYADMIN_PORT}:80
        depends_on:
          - mysql

    
    