version: '3'
services:
    app:
        image: manzolo/voltwatcher_app
        restart: always
        build: 
          context: .
          dockerfile: .docker/full/php/Dockerfile
        container_name: voltwatcher_app
        volumes:
            - ./var:/app/var
            - ./config/jwt:/app/config/jwt
        environment:
          APP_ENV: ${APP_ENV}
          DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@voltwatcher_mysql:3306/${MYSQL_DATABASE}
          JWT_PASSPHRASE: ${JWT_PASSPHRASE}
          MAILER_USER: ${MAILER_USER}
          OPENWEATHERMAP_APIKEY: ${OPENWEATHERMAP_APIKEY}
          MAILER_DSN: ${MAILER_DSN}
        ports:
            - ${APACHE_PORT}:8001
