version: '3'
 
services:
 
  voltwatcher_database:
    build:
      context: ./mysql
    image: '${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_mysql:${IMAGE_TAG}'
    container_name: '${REPOSITORY_NAME}_mysql'
    hostname: '${REPOSITORY_NAME}-mysql'
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ../var/log/docker/mysql:/var/log/mysql:consistent
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
 
  voltwatcher_php:
    build:
      context: ./php
    image: '${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_php:${IMAGE_TAG}'
    container_name: '${REPOSITORY_NAME}_php'
    hostname: '${REPOSITORY_NAME}-php'
    volumes:
      - ..:/app:consistent
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
    working_dir: /app

    depends_on:
      - voltwatcher_database
    
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@voltwatcher_database:3306/${MYSQL_DATABASE}?serverVersion=5.7
      - locale=it
      
  voltwatcher_nginx:
    build:
      context: ./nginx
    image: '${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_nginx:${IMAGE_TAG}'
    container_name: '${REPOSITORY_NAME}_nginx'
    hostname: '${REPOSITORY_NAME}-nginx'
    ports:
      - '8081:80'
    volumes:
      - ..:/app:consistent
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../var/log/docker/nginx:/var/log/nginx:consistent
    depends_on:
      - voltwatcher_database
      - voltwatcher_php

#chmod -R 777 var/log/
#docker exec -it voltwatcher_php bin/console bicorebundle:install voltwatcherusr voltwatcherpwd voltwatcherusr@email.it
#docker-compose up -d --build
#docker-compose stop
#docker-compose down --rmi all
#docker exec -it voltwatcher_php /bin/bash





