version: '3'
services:
  app:
    image: manzolo/voltwatcher
    container_name: voltwatcher_php
    build: 
      context: ../../.
      dockerfile: docker/nodb/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ../../.env.local
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: voltwatcher_mysql
    volumes:
        - .docker/data/db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: voltwatcher_phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
          - 8002:80
      links:
          - mysql